#!/bin/bash

set -e -u
set -o pipefail

env_dir=${HOME}/workspace/deployments/lite

cf api api.bosh-lite.com --skip-ssl-validation
adminpw=$(grep cf_admin_password $env_dir/deployment-vars.yml | cut -d ' ' -f2)
cf auth admin "$adminpw"
