#!/bin/bash

set -e -u
set -o pipefail

env_dir=${HOME}/workspace/deployments/lite

bosh create-env ~/workspace/bosh-deployment/bosh.yml \
--state $env_dir/state.json \
-o ~/workspace/bosh-deployment/virtualbox/cpi.yml \
-o ~/workspace/bosh-deployment/virtualbox/outbound-network.yml \
-o ~/workspace/bosh-deployment/bosh-lite.yml \
-o ~/workspace/bosh-deployment/bosh-lite-runc.yml \
-o ~/workspace/bosh-deployment/jumpbox-user.yml \
-o ~/workspace/bosh-deployment/local-dns.yml \
--vars-store $env_dir/creds.yml \
-v director_name="Bosh Lite Director" \
-v internal_ip=192.168.50.6 \
-v internal_gw=192.168.50.1 \
-v internal_cidr=192.168.50.0/24 \
-v outbound_network_name="NatNetwork"

bosh -e 192.168.50.6 --ca-cert <(bosh int $env_dir/creds.yml --path /director_ssl/ca) alias-env vbox
BOSH_CLIENT="admin"
BOSH_CLIENT_SECRET="$(bosh int $env_dir/creds.yml --path /admin_password)"
BOSH_ENVIRONMENT="vbox"
BOSH_DEPLOYMENT="cf"
BOSH_CA_CERT="/tmp/bosh-lite-ca-cert"

export BOSH_CLIENT
export BOSH_CLIENT_SECRET
export BOSH_ENVIRONMENT
export BOSH_DEPLOYMENT
export BOSH_CA_CERT
bosh int $env_dir/creds.yml --path /director_ssl/ca > ${BOSH_CA_CERT}

STEMCELL_VERSION="$(bosh int ~/workspace/cf-deployment/cf-deployment.yml --path=/stemcells/0/version)"
echo "will upload stemcell ${STEMCELL_VERSION}"
bosh -e vbox upload-stemcell "https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent?v=${STEMCELL_VERSION}"

bosh -e vbox -n update-cloud-config ~/workspace/cf-deployment/iaas-support/bosh-lite/cloud-config.yml

sudo route add -net "10.244.0.0/16" "192.168.50.6"
